### ISSUE TITLE
Not working with sanic==20.12.1

### ISSUE THREAD

**Issue by 4doge** [omarryhan/sanic-cookies#4]
Hello there,

Not working, getting `AttributeError: 'Request' object has no attribute 'session'`, since Sanic change the way how you should access/modify the Request instance. 

Read more - https://github.com/xen/sanic_session/issues/62

Regars

**Comment by omarryhan** [comment]
Hello Anton,

This change has been in my mental-backlog for a while now. I was waiting for Sanic to deprecate their previous LTS version, so that we wouldn't have to support two different APIs. Now that their previous LTS is got deprecated, I'll try to fix this as soon as I get the time. Meanwhile, I'll be more than happy to accept a PR.

Thanks for raising the issue.

**Comment by psylopunk** [comment]
> Hello Anton,
> 
> This change has been in my mental-backlog for a while now. I was waiting for Sanic to deprecate their previous LTS version, so that we wouldn't have to support two different APIs. Now that their previous LTS is got deprecated, I'll try to fix this as soon as I get the time. Meanwhile, I'll be more than happy to accept a PR.
> 
> Thanks for raising the issue.

But, with which version of sanic is library working stably now? :)

**Comment by omarryhan** [comment]
Good question! I honestly can't remember, should've written it down in the README when the breaking change happened. Last version I see working in my old apps was v19.6.0
